import { useMemo, useState } from 'react'; import { ToolLayout } from '../../shared/components/ToolLayout'; import { renderTool } from '../../shared/toolEntry'; import './styles.css';
function decodePart(part:string) { const base=part.replace(/-/g,'+').replace(/_/g,'/'); const normalized=base.padEnd(Math.ceil(base.length/4)*4,'='); const bytes=Uint8Array.from(atob(normalized), c=>c.charCodeAt(0)); return JSON.parse(new TextDecoder().decode(bytes)); }
function App(){ const [token,setToken]=useState(''); const parts=token.trim().split('.'); const decoded=useMemo(()=>{try{if(parts.length!==3) throw new Error('Um JWT deve ter três partes separadas por pontos.');return {header:decodePart(parts[0]),payload:decodePart(parts[1]),signature:parts[2]};}catch(e){return {error:e instanceof Error?e.message:'Token inválido'};}},[token]); return <ToolLayout name="JWT Decoder" title={<>Entenda seu <em>JWT</em></>} description="Decodifique header e payload. A assinatura não é validada.">
  <div className="form-field"><label htmlFor="jwt">Token JWT</label><textarea className="mono" id="jwt" value={token} onChange={e=>setToken(e.target.value)} placeholder="eyJhbGciOi..." /></div>
  {parts.length === 3 && <div className="jwt-segments" aria-label="Segmentos do token"><span className="header-part">{parts[0]}</span><b>.</b><span className="payload-part">{parts[1]}</span><b>.</b><span className="signature-part">{parts[2]}</span></div>}
  <div className="jwt-legend"><span className="header-part">Header</span><span className="payload-part">Payload</span><span className="signature-part">Assinatura</span></div>
  {'error' in decoded ? <p className="error-text">{decoded.error}</p> : <div className="jwt-decoded"><div className="form-field header-panel"><label>Header</label><textarea className="mono" readOnly value={JSON.stringify(decoded.header,null,2)} /></div><div className="form-field payload-panel"><label>Payload</label><textarea className="mono" readOnly value={JSON.stringify(decoded.payload,null,2)} /></div><div className="form-field signature-panel"><label>Assinatura codificada</label><textarea className="mono" readOnly value={decoded.signature} /></div></div>}
  <p style={{color:'var(--muted)',fontSize:12}}>Decodificar não confirma autenticidade. Nunca confie no conteúdo sem verificar a assinatura no servidor.</p>
  </ToolLayout>;} renderTool(<App/>);
